name: Site Monitoring

on:
  schedule:
    # Daily monitoring at 8 AM UTC (comprehensive check)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual runs
    inputs:
      check_type:
        description: 'Type of check to run'
        required: false
        default: 'both'
        type: choice
        options:
        - uptime
        - lighthouse
        - both

permissions:
  contents: write

jobs:
  monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run comprehensive monitoring
      id: monitoring
      run: |
        echo "Running daily comprehensive monitoring..."
        npm run uptime
        npm run lighthouse  
        npm run matomo
        npm run shopify-orders
        npm run wordpress-integrity
        echo "monitoring_success=true" >> $GITHUB_OUTPUT
      continue-on-error: true
      env:
        MATOMO_TOKEN: ${{ secrets.MATOMO_TOKEN }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

    - name: Send alerts if critical issues detected
      if: steps.monitoring.outcome == 'failure'
      run: |
        npm run alerts
        npm run advanced-alerts
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DS_WEBHOOK_URL }}

    - name: Send daily status report
      if: steps.monitoring.outcome == 'success'
      run: |
        npm run status
        npm run advanced-status
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DS_WEBHOOK_URL }}

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if ! git diff --staged --quiet; then
          git commit -m "📊 Daily monitoring report - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        else
          echo "No changes to commit"
        fi