name: Site Monitoring

on:
  schedule:
    # Uptime checks every 30 minutes
    - cron: '*/30 * * * *'
    # Performance checks every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual runs
    inputs:
      check_type:
        description: 'Type of check to run'
        required: false
        default: 'both'
        type: choice
        options:
        - uptime
        - lighthouse
        - both

permissions:
  contents: write

jobs:
  uptime-check:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/30 * * * *' || github.event_name == 'workflow_dispatch' && (github.event.inputs.check_type == 'uptime' || github.event.inputs.check_type == 'both')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run uptime checks
      id: uptime
      run: |
        npm run uptime
        echo "uptime_success=true" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Send alerts if uptime failed
      if: steps.uptime.outcome == 'failure'
      run: npm run alerts
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/uptime/
        if ! git diff --staged --quiet; then
          git commit -m "📊 Uptime check results - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        else
          echo "No changes to commit"
        fi

  lighthouse-check:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 */6 * * *' || github.event_name == 'workflow_dispatch' && (github.event.inputs.check_type == 'lighthouse' || github.event.inputs.check_type == 'both')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli

    - name: Run Lighthouse audits
      id: lighthouse
      run: |
        npm run lighthouse
        echo "lighthouse_success=true" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Send alerts if performance failed
      if: steps.lighthouse.outcome == 'failure'
      run: npm run alerts
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/perf/
        if ! git diff --staged --quiet; then
          git commit -m "🚀 Lighthouse audit results - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        else
          echo "No changes to commit"
        fi